/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TocRouteImport } from './routes/toc'
import { Route as PpRouteImport } from './routes/pp'
import { Route as GuardedRouteImport } from './routes/_guarded'
import { Route as gateIndexRouteImport } from './routes/(gate)/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthPasswordResetRouteImport } from './routes/auth/password-reset'
import { Route as GuardedPlayRouteImport } from './routes/_guarded/play'
import { Route as GuardedCatIdRouteImport } from './routes/_guarded/$catId'
import { Route as GuardedConfigIndexRouteImport } from './routes/_guarded/config/index'
import { Route as GuardedCatSummonRouteImport } from './routes/_guarded/cat/summon'
import { Route as GuardedCatIdPlayIndexRouteImport } from './routes/_guarded/$catId/play/index'
import { Route as GuardedCatIdCatStatusRouteImport } from './routes/_guarded/$catId/cat/status'
import { Route as GuardedCatIdCatCareHistoryRouteImport } from './routes/_guarded/$catId/cat/care-history'
import { Route as GuardedCatIdCatPersonalityIndexRouteImport } from './routes/_guarded/$catId/cat/personality/index'
import { Route as GuardedCatIdCatPersonalityIntroductionRouteImport } from './routes/_guarded/$catId/cat/personality/introduction'

const TocRoute = TocRouteImport.update({
  id: '/toc',
  path: '/toc',
  getParentRoute: () => rootRouteImport,
} as any)
const PpRoute = PpRouteImport.update({
  id: '/pp',
  path: '/pp',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardedRoute = GuardedRouteImport.update({
  id: '/_guarded',
  getParentRoute: () => rootRouteImport,
} as any)
const gateIndexRoute = gateIndexRouteImport.update({
  id: '/(gate)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/auth/password-reset',
  path: '/auth/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardedPlayRoute = GuardedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => GuardedRoute,
} as any)
const GuardedCatIdRoute = GuardedCatIdRouteImport.update({
  id: '/$catId',
  path: '/$catId',
  getParentRoute: () => GuardedRoute,
} as any)
const GuardedConfigIndexRoute = GuardedConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => GuardedRoute,
} as any)
const GuardedCatSummonRoute = GuardedCatSummonRouteImport.update({
  id: '/cat/summon',
  path: '/cat/summon',
  getParentRoute: () => GuardedRoute,
} as any)
const GuardedCatIdPlayIndexRoute = GuardedCatIdPlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => GuardedCatIdRoute,
} as any)
const GuardedCatIdCatStatusRoute = GuardedCatIdCatStatusRouteImport.update({
  id: '/cat/status',
  path: '/cat/status',
  getParentRoute: () => GuardedCatIdRoute,
} as any)
const GuardedCatIdCatCareHistoryRoute =
  GuardedCatIdCatCareHistoryRouteImport.update({
    id: '/cat/care-history',
    path: '/cat/care-history',
    getParentRoute: () => GuardedCatIdRoute,
  } as any)
const GuardedCatIdCatPersonalityIndexRoute =
  GuardedCatIdCatPersonalityIndexRouteImport.update({
    id: '/cat/personality/',
    path: '/cat/personality/',
    getParentRoute: () => GuardedCatIdRoute,
  } as any)
const GuardedCatIdCatPersonalityIntroductionRoute =
  GuardedCatIdCatPersonalityIntroductionRouteImport.update({
    id: '/cat/personality/introduction',
    path: '/cat/personality/introduction',
    getParentRoute: () => GuardedCatIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof gateIndexRoute
  '/pp': typeof PpRoute
  '/toc': typeof TocRoute
  '/$catId': typeof GuardedCatIdRouteWithChildren
  '/play': typeof GuardedPlayRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cat/summon': typeof GuardedCatSummonRoute
  '/config/': typeof GuardedConfigIndexRoute
  '/$catId/cat/care-history': typeof GuardedCatIdCatCareHistoryRoute
  '/$catId/cat/status': typeof GuardedCatIdCatStatusRoute
  '/$catId/play/': typeof GuardedCatIdPlayIndexRoute
  '/$catId/cat/personality/introduction': typeof GuardedCatIdCatPersonalityIntroductionRoute
  '/$catId/cat/personality/': typeof GuardedCatIdCatPersonalityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof gateIndexRoute
  '/pp': typeof PpRoute
  '/toc': typeof TocRoute
  '/$catId': typeof GuardedCatIdRouteWithChildren
  '/play': typeof GuardedPlayRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cat/summon': typeof GuardedCatSummonRoute
  '/config': typeof GuardedConfigIndexRoute
  '/$catId/cat/care-history': typeof GuardedCatIdCatCareHistoryRoute
  '/$catId/cat/status': typeof GuardedCatIdCatStatusRoute
  '/$catId/play': typeof GuardedCatIdPlayIndexRoute
  '/$catId/cat/personality/introduction': typeof GuardedCatIdCatPersonalityIntroductionRoute
  '/$catId/cat/personality': typeof GuardedCatIdCatPersonalityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guarded': typeof GuardedRouteWithChildren
  '/pp': typeof PpRoute
  '/toc': typeof TocRoute
  '/_guarded/$catId': typeof GuardedCatIdRouteWithChildren
  '/_guarded/play': typeof GuardedPlayRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/(gate)/': typeof gateIndexRoute
  '/_guarded/cat/summon': typeof GuardedCatSummonRoute
  '/_guarded/config/': typeof GuardedConfigIndexRoute
  '/_guarded/$catId/cat/care-history': typeof GuardedCatIdCatCareHistoryRoute
  '/_guarded/$catId/cat/status': typeof GuardedCatIdCatStatusRoute
  '/_guarded/$catId/play/': typeof GuardedCatIdPlayIndexRoute
  '/_guarded/$catId/cat/personality/introduction': typeof GuardedCatIdCatPersonalityIntroductionRoute
  '/_guarded/$catId/cat/personality/': typeof GuardedCatIdCatPersonalityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pp'
    | '/toc'
    | '/$catId'
    | '/play'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/sign-in'
    | '/cat/summon'
    | '/config/'
    | '/$catId/cat/care-history'
    | '/$catId/cat/status'
    | '/$catId/play/'
    | '/$catId/cat/personality/introduction'
    | '/$catId/cat/personality/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pp'
    | '/toc'
    | '/$catId'
    | '/play'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/sign-in'
    | '/cat/summon'
    | '/config'
    | '/$catId/cat/care-history'
    | '/$catId/cat/status'
    | '/$catId/play'
    | '/$catId/cat/personality/introduction'
    | '/$catId/cat/personality'
  id:
    | '__root__'
    | '/_guarded'
    | '/pp'
    | '/toc'
    | '/_guarded/$catId'
    | '/_guarded/play'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/sign-in'
    | '/(gate)/'
    | '/_guarded/cat/summon'
    | '/_guarded/config/'
    | '/_guarded/$catId/cat/care-history'
    | '/_guarded/$catId/cat/status'
    | '/_guarded/$catId/play/'
    | '/_guarded/$catId/cat/personality/introduction'
    | '/_guarded/$catId/cat/personality/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuardedRoute: typeof GuardedRouteWithChildren
  PpRoute: typeof PpRoute
  TocRoute: typeof TocRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSignInRoute: typeof AuthSignInRoute
  gateIndexRoute: typeof gateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toc': {
      id: '/toc'
      path: '/toc'
      fullPath: '/toc'
      preLoaderRoute: typeof TocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pp': {
      id: '/pp'
      path: '/pp'
      fullPath: '/pp'
      preLoaderRoute: typeof PpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guarded': {
      id: '/_guarded'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuardedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(gate)/': {
      id: '/(gate)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof gateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password-reset': {
      id: '/auth/password-reset'
      path: '/auth/password-reset'
      fullPath: '/auth/password-reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guarded/play': {
      id: '/_guarded/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof GuardedPlayRouteImport
      parentRoute: typeof GuardedRoute
    }
    '/_guarded/$catId': {
      id: '/_guarded/$catId'
      path: '/$catId'
      fullPath: '/$catId'
      preLoaderRoute: typeof GuardedCatIdRouteImport
      parentRoute: typeof GuardedRoute
    }
    '/_guarded/config/': {
      id: '/_guarded/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof GuardedConfigIndexRouteImport
      parentRoute: typeof GuardedRoute
    }
    '/_guarded/cat/summon': {
      id: '/_guarded/cat/summon'
      path: '/cat/summon'
      fullPath: '/cat/summon'
      preLoaderRoute: typeof GuardedCatSummonRouteImport
      parentRoute: typeof GuardedRoute
    }
    '/_guarded/$catId/play/': {
      id: '/_guarded/$catId/play/'
      path: '/play'
      fullPath: '/$catId/play/'
      preLoaderRoute: typeof GuardedCatIdPlayIndexRouteImport
      parentRoute: typeof GuardedCatIdRoute
    }
    '/_guarded/$catId/cat/status': {
      id: '/_guarded/$catId/cat/status'
      path: '/cat/status'
      fullPath: '/$catId/cat/status'
      preLoaderRoute: typeof GuardedCatIdCatStatusRouteImport
      parentRoute: typeof GuardedCatIdRoute
    }
    '/_guarded/$catId/cat/care-history': {
      id: '/_guarded/$catId/cat/care-history'
      path: '/cat/care-history'
      fullPath: '/$catId/cat/care-history'
      preLoaderRoute: typeof GuardedCatIdCatCareHistoryRouteImport
      parentRoute: typeof GuardedCatIdRoute
    }
    '/_guarded/$catId/cat/personality/': {
      id: '/_guarded/$catId/cat/personality/'
      path: '/cat/personality'
      fullPath: '/$catId/cat/personality/'
      preLoaderRoute: typeof GuardedCatIdCatPersonalityIndexRouteImport
      parentRoute: typeof GuardedCatIdRoute
    }
    '/_guarded/$catId/cat/personality/introduction': {
      id: '/_guarded/$catId/cat/personality/introduction'
      path: '/cat/personality/introduction'
      fullPath: '/$catId/cat/personality/introduction'
      preLoaderRoute: typeof GuardedCatIdCatPersonalityIntroductionRouteImport
      parentRoute: typeof GuardedCatIdRoute
    }
  }
}

interface GuardedCatIdRouteChildren {
  GuardedCatIdCatCareHistoryRoute: typeof GuardedCatIdCatCareHistoryRoute
  GuardedCatIdCatStatusRoute: typeof GuardedCatIdCatStatusRoute
  GuardedCatIdPlayIndexRoute: typeof GuardedCatIdPlayIndexRoute
  GuardedCatIdCatPersonalityIntroductionRoute: typeof GuardedCatIdCatPersonalityIntroductionRoute
  GuardedCatIdCatPersonalityIndexRoute: typeof GuardedCatIdCatPersonalityIndexRoute
}

const GuardedCatIdRouteChildren: GuardedCatIdRouteChildren = {
  GuardedCatIdCatCareHistoryRoute: GuardedCatIdCatCareHistoryRoute,
  GuardedCatIdCatStatusRoute: GuardedCatIdCatStatusRoute,
  GuardedCatIdPlayIndexRoute: GuardedCatIdPlayIndexRoute,
  GuardedCatIdCatPersonalityIntroductionRoute:
    GuardedCatIdCatPersonalityIntroductionRoute,
  GuardedCatIdCatPersonalityIndexRoute: GuardedCatIdCatPersonalityIndexRoute,
}

const GuardedCatIdRouteWithChildren = GuardedCatIdRoute._addFileChildren(
  GuardedCatIdRouteChildren,
)

interface GuardedRouteChildren {
  GuardedCatIdRoute: typeof GuardedCatIdRouteWithChildren
  GuardedPlayRoute: typeof GuardedPlayRoute
  GuardedCatSummonRoute: typeof GuardedCatSummonRoute
  GuardedConfigIndexRoute: typeof GuardedConfigIndexRoute
}

const GuardedRouteChildren: GuardedRouteChildren = {
  GuardedCatIdRoute: GuardedCatIdRouteWithChildren,
  GuardedPlayRoute: GuardedPlayRoute,
  GuardedCatSummonRoute: GuardedCatSummonRoute,
  GuardedConfigIndexRoute: GuardedConfigIndexRoute,
}

const GuardedRouteWithChildren =
  GuardedRoute._addFileChildren(GuardedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GuardedRoute: GuardedRouteWithChildren,
  PpRoute: PpRoute,
  TocRoute: TocRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSignInRoute: AuthSignInRoute,
  gateIndexRoute: gateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
