/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TocRouteImport } from './routes/toc'
import { Route as PpRouteImport } from './routes/pp'
import { Route as GuardedRouteImport } from './routes/_guarded'
import { Route as gateIndexRouteImport } from './routes/(gate)/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthPasswordResetRouteImport } from './routes/auth/password-reset'
import { Route as GuardedPlayIndexRouteImport } from './routes/_guarded/play/index'
import { Route as GuardedCatSummonRouteImport } from './routes/_guarded/cat/summon'
import { Route as GuardedCatStatusRouteImport } from './routes/_guarded/cat/status'
import { Route as GuardedCatCareHistoryRouteImport } from './routes/_guarded/cat/care-history'

const TocRoute = TocRouteImport.update({
  id: '/toc',
  path: '/toc',
  getParentRoute: () => rootRouteImport,
} as any)
const PpRoute = PpRouteImport.update({
  id: '/pp',
  path: '/pp',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardedRoute = GuardedRouteImport.update({
  id: '/_guarded',
  getParentRoute: () => rootRouteImport,
} as any)
const gateIndexRoute = gateIndexRouteImport.update({
  id: '/(gate)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/auth/password-reset',
  path: '/auth/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardedPlayIndexRoute = GuardedPlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => GuardedRoute,
} as any)
const GuardedCatSummonRoute = GuardedCatSummonRouteImport.update({
  id: '/cat/summon',
  path: '/cat/summon',
  getParentRoute: () => GuardedRoute,
} as any)
const GuardedCatStatusRoute = GuardedCatStatusRouteImport.update({
  id: '/cat/status',
  path: '/cat/status',
  getParentRoute: () => GuardedRoute,
} as any)
const GuardedCatCareHistoryRoute = GuardedCatCareHistoryRouteImport.update({
  id: '/cat/care-history',
  path: '/cat/care-history',
  getParentRoute: () => GuardedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof gateIndexRoute
  '/pp': typeof PpRoute
  '/toc': typeof TocRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cat/care-history': typeof GuardedCatCareHistoryRoute
  '/cat/status': typeof GuardedCatStatusRoute
  '/cat/summon': typeof GuardedCatSummonRoute
  '/play/': typeof GuardedPlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof gateIndexRoute
  '/pp': typeof PpRoute
  '/toc': typeof TocRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cat/care-history': typeof GuardedCatCareHistoryRoute
  '/cat/status': typeof GuardedCatStatusRoute
  '/cat/summon': typeof GuardedCatSummonRoute
  '/play': typeof GuardedPlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guarded': typeof GuardedRouteWithChildren
  '/pp': typeof PpRoute
  '/toc': typeof TocRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/(gate)/': typeof gateIndexRoute
  '/_guarded/cat/care-history': typeof GuardedCatCareHistoryRoute
  '/_guarded/cat/status': typeof GuardedCatStatusRoute
  '/_guarded/cat/summon': typeof GuardedCatSummonRoute
  '/_guarded/play/': typeof GuardedPlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pp'
    | '/toc'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/sign-in'
    | '/cat/care-history'
    | '/cat/status'
    | '/cat/summon'
    | '/play/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pp'
    | '/toc'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/sign-in'
    | '/cat/care-history'
    | '/cat/status'
    | '/cat/summon'
    | '/play'
  id:
    | '__root__'
    | '/_guarded'
    | '/pp'
    | '/toc'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/sign-in'
    | '/(gate)/'
    | '/_guarded/cat/care-history'
    | '/_guarded/cat/status'
    | '/_guarded/cat/summon'
    | '/_guarded/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuardedRoute: typeof GuardedRouteWithChildren
  PpRoute: typeof PpRoute
  TocRoute: typeof TocRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSignInRoute: typeof AuthSignInRoute
  gateIndexRoute: typeof gateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toc': {
      id: '/toc'
      path: '/toc'
      fullPath: '/toc'
      preLoaderRoute: typeof TocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pp': {
      id: '/pp'
      path: '/pp'
      fullPath: '/pp'
      preLoaderRoute: typeof PpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guarded': {
      id: '/_guarded'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuardedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(gate)/': {
      id: '/(gate)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof gateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password-reset': {
      id: '/auth/password-reset'
      path: '/auth/password-reset'
      fullPath: '/auth/password-reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guarded/play/': {
      id: '/_guarded/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof GuardedPlayIndexRouteImport
      parentRoute: typeof GuardedRoute
    }
    '/_guarded/cat/summon': {
      id: '/_guarded/cat/summon'
      path: '/cat/summon'
      fullPath: '/cat/summon'
      preLoaderRoute: typeof GuardedCatSummonRouteImport
      parentRoute: typeof GuardedRoute
    }
    '/_guarded/cat/status': {
      id: '/_guarded/cat/status'
      path: '/cat/status'
      fullPath: '/cat/status'
      preLoaderRoute: typeof GuardedCatStatusRouteImport
      parentRoute: typeof GuardedRoute
    }
    '/_guarded/cat/care-history': {
      id: '/_guarded/cat/care-history'
      path: '/cat/care-history'
      fullPath: '/cat/care-history'
      preLoaderRoute: typeof GuardedCatCareHistoryRouteImport
      parentRoute: typeof GuardedRoute
    }
  }
}

interface GuardedRouteChildren {
  GuardedCatCareHistoryRoute: typeof GuardedCatCareHistoryRoute
  GuardedCatStatusRoute: typeof GuardedCatStatusRoute
  GuardedCatSummonRoute: typeof GuardedCatSummonRoute
  GuardedPlayIndexRoute: typeof GuardedPlayIndexRoute
}

const GuardedRouteChildren: GuardedRouteChildren = {
  GuardedCatCareHistoryRoute: GuardedCatCareHistoryRoute,
  GuardedCatStatusRoute: GuardedCatStatusRoute,
  GuardedCatSummonRoute: GuardedCatSummonRoute,
  GuardedPlayIndexRoute: GuardedPlayIndexRoute,
}

const GuardedRouteWithChildren =
  GuardedRoute._addFileChildren(GuardedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GuardedRoute: GuardedRouteWithChildren,
  PpRoute: PpRoute,
  TocRoute: TocRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSignInRoute: AuthSignInRoute,
  gateIndexRoute: gateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
